services:
  - type: web
    name: eaglerproxy
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npx ts-node src/index.ts
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
