services:
  - type: web
    name: eaglerproxy
    env: node
    buildCommand: |
      npm install
      tsc
    startCommand: node build/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: EAGLERPROXY_HOST
        value: "0.0.0.0"
      - key: EAGLERPROXY_PORT
        value: "8080"
      - key: EAGLERPROXY_SERVER_HOST
        value: "your.server.host"
      - key: EAGLERPROXY_SERVER_PORT
        value: "25565"
      - key: EAGLERPROXY_TLS_CERT_PATH
        value: "/path/to/cert.pem"
      - key: EAGLERPROXY_TLS_KEY_PATH
        value: "/path/to/key.pem"
    plan: free
    region: oregon
    autoDeploy: true
    branch: main
    repo: https://github.com/WorldEditAxe/eaglerproxy
